spring:
  application:
    name: backend-content
server:
  port: 9021
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#分布式事务
tx-lcn:
  client:
    manager-address: 127.0.0.1:8070